// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/snyk-go/pkg/models/shared"
	"net/http"
)

type GetAccountQueryParams struct {
	// The token for the customer's CRM account. This was generated when they connected their account.
	AccessToken string `queryParam:"style=form,explode=true,name=accessToken"`
	// Returns all fields including non-unifiable and custom fields under the "additional" property in the response
	AllFields *bool  `queryParam:"style=form,explode=true,name=allFields"`
	ID        string `queryParam:"style=form,explode=true,name=id"`
}

type GetAccountRequest struct {
	QueryParams GetAccountQueryParams
}

// GetAccount200ApplicationJSON - OK
type GetAccount200ApplicationJSON struct {
	// (Alias: company, organization) An organization involved with your business.
	Account *shared.Account `json:"account,omitempty"`
}

type GetAccountResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	GetAccount200ApplicationJSONObject *GetAccount200ApplicationJSON
}
