// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/snyk-go/pkg/models/shared"
	"net/http"
)

type GetCrmUsersQueryParams struct {
	// The token for the customer's CRM account. This was generated when they connected their account.
	AccessToken string `queryParam:"style=form,explode=true,name=accessToken"`
	// Returns all fields including non-unifiable and custom fields under the "additional" property in the response
	AllFields *bool   `queryParam:"style=form,explode=true,name=allFields"`
	Cursor    *string `queryParam:"style=form,explode=true,name=cursor"`
}

type GetCrmUsersRequest struct {
	QueryParams GetCrmUsersQueryParams
}

// GetCrmUsers200ApplicationJSON - OK
type GetCrmUsers200ApplicationJSON struct {
	NextPageCursor *string       `json:"nextPageCursor,omitempty"`
	Users          []shared.User `json:"users,omitempty"`
}

type GetCrmUsersResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	GetCrmUsers200ApplicationJSONObject *GetCrmUsers200ApplicationJSON
}
