// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/snyk-go/pkg/models/shared"
	"net/http"
)

type GetContactRequest struct {
	// The token for the customer's CRM account. This was generated when they connected their account.
	AccessToken string `queryParam:"style=form,explode=true,name=accessToken"`
	// Returns all fields including non-unifiable and custom fields under the "additional" property in the response
	AllFields *bool `queryParam:"style=form,explode=true,name=allFields"`
	// The email of the contact to get (concedes precedence over id when both are included)
	Email *string `queryParam:"style=form,explode=true,name=email"`
	// The id of the contact to get (takes precedence over email when both are included)
	ID *string `queryParam:"style=form,explode=true,name=id"`
}

// GetContact200ApplicationJSON - OK
type GetContact200ApplicationJSON struct {
	// Information about an individual affiliated with another CRM Object (e.g., a Lead, a Deal, etc)
	Contact *shared.Contact `json:"contact,omitempty"`
}

type GetContactResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	GetContact200ApplicationJSONObject *GetContact200ApplicationJSON
}
