// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/snyk-go/pkg/models/shared"
	"net/http"
)

// GetConnections200ApplicationJSON - OK
type GetConnections200ApplicationJSON struct {
	Connections []shared.Connection `json:"connections,omitempty"`
}

type GetConnectionsResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	GetConnections200ApplicationJSONObject *GetConnections200ApplicationJSON
}
