// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/snyk-go/pkg/models/shared"
	"net/http"
)

type GetConnectionQueryParams struct {
	// The token for the customer's CRM account. This was generated when they connected their account.
	AccessToken string `queryParam:"style=form,explode=true,name=accessToken"`
}

type GetConnectionRequest struct {
	QueryParams GetConnectionQueryParams
}

// GetConnection200ApplicationJSON - OK
type GetConnection200ApplicationJSON struct {
	Connection *shared.Connection `json:"connection,omitempty"`
}

type GetConnectionResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	GetConnection200ApplicationJSONObject *GetConnection200ApplicationJSON
}
