// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/snyk-go/pkg/models/shared"
	"net/http"
)

type GetDealQueryParams struct {
	// The token for the customer's CRM account. This was generated when they connected their account.
	AccessToken string `queryParam:"style=form,explode=true,name=accessToken"`
	// Returns all fields including non-unifiable and custom fields under the "additional" property in the response
	AllFields *bool  `queryParam:"style=form,explode=true,name=allFields"`
	ID        string `queryParam:"style=form,explode=true,name=id"`
}

type GetDealRequest struct {
	QueryParams GetDealQueryParams
}

// GetDeal200ApplicationJSON - OK
type GetDeal200ApplicationJSON struct {
	// (Alias: Opportunity) An object representing either the opportunity to sell a product to an Account, or in the case of an `isWon` deal, a product sold to an Account.
	//
	//
	// *CRM Caveats*:
	// - Pipedrive: Users must have "Deal probability" turned on for the given pipeline for probability to be configurable and returned.
	Deal *shared.Deal `json:"deal,omitempty"`
}

type GetDealResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	GetDeal200ApplicationJSONObject *GetDeal200ApplicationJSON
}
