// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/snyk-go/pkg/models/shared"
	"net/http"
)

type GetDealDetailsRequest struct {
	// The token for the customer's CRM account. This was generated when they connected their account.
	AccessToken string `queryParam:"style=form,explode=true,name=accessToken"`
	// Returns details about native fields.
	AllFields *bool   `queryParam:"style=form,explode=true,name=allFields"`
	Cursor    *string `queryParam:"style=form,explode=true,name=cursor"`
	// If provided, get the details about a particular deal. If not provided, get details about all deals.
	ID *string `queryParam:"style=form,explode=true,name=id"`
}

// GetDealDetails200ApplicationJSON - OK
type GetDealDetails200ApplicationJSON struct {
	Fields         []shared.Field `json:"fields,omitempty"`
	NextPageCursor *string        `json:"nextPageCursor,omitempty"`
}

type GetDealDetailsResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	GetDealDetails200ApplicationJSONObject *GetDealDetails200ApplicationJSON
}
