// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/snyk-go/pkg/models/shared"
	"net/http"
)

type GetEventAttendeeRequest struct {
	// The token for the customer's CRM account. This was generated when they connected their account.
	AccessToken string `queryParam:"style=form,explode=true,name=accessToken"`
	// Returns all fields including non-unifiable and custom fields under the "additional" property in the response
	AllFields *bool  `queryParam:"style=form,explode=true,name=allFields"`
	ID        string `queryParam:"style=form,explode=true,name=id"`
}

// GetEventAttendee200ApplicationJSON - OK
type GetEventAttendee200ApplicationJSON struct {
	// Event Attendees hold information about someone who attendeed or was invited to an event. Attendees are always associated with some Event and another person object such as a Contact, Lead, or Other.
	EventAttendee *shared.EventAttendee `json:"eventAttendee,omitempty"`
}

type GetEventAttendeeResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	GetEventAttendee200ApplicationJSONObject *GetEventAttendee200ApplicationJSON
}
