// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/snyk-go/pkg/models/shared"
	"net/http"
)

// GetIntegrations200ApplicationJSON - OK
type GetIntegrations200ApplicationJSON struct {
	Integrations []shared.CrmIntegration `json:"integrations,omitempty"`
}

type GetIntegrationsResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	GetIntegrations200ApplicationJSONObject *GetIntegrations200ApplicationJSON
}
