// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/snyk-go/pkg/models/shared"
	"net/http"
)

type GetLeadRequest struct {
	// The token for the customer's CRM account. This was generated when they connected their account.
	AccessToken string `queryParam:"style=form,explode=true,name=accessToken"`
	// Returns all fields including non-unifiable and custom fields under the "additional" property in the response
	AllFields *bool  `queryParam:"style=form,explode=true,name=allFields"`
	ID        string `queryParam:"style=form,explode=true,name=id"`
}

// GetLead200ApplicationJSON - OK
type GetLead200ApplicationJSON struct {
	// A Lead represents an individual, or sometimes an organization, that is interested in purchasing your product (i.e., is a potential Deal).
	//
	// *CRM Caveats*:
	// - HubSpot: we consider contacts with the `leadStatus` set to be leads.
	Lead *shared.Lead `json:"lead,omitempty"`
}

type GetLeadResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	GetLead200ApplicationJSONObject *GetLead200ApplicationJSON
}
