// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/snyk-go/pkg/models/shared"
	"net/http"
)

type GetNoteQueryParams struct {
	// The token for the customer's CRM account. This was generated when they connected their account.
	AccessToken string `queryParam:"style=form,explode=true,name=accessToken"`
	// Returns all fields including non-unifiable and custom fields under the "additional" property in the response
	AllFields *bool  `queryParam:"style=form,explode=true,name=allFields"`
	ID        string `queryParam:"style=form,explode=true,name=id"`
}

type GetNoteRequest struct {
	QueryParams GetNoteQueryParams
}

// GetNote200ApplicationJSON - OK
type GetNote200ApplicationJSON struct {
	// A Note attached to some CRM Object.
	Note *shared.Note `json:"note,omitempty"`
}

type GetNoteResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	GetNote200ApplicationJSONObject *GetNote200ApplicationJSON
}
