// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/snyk-go/pkg/models/shared"
	"net/http"
)

type GetUserQueryParams struct {
	// The token for the customer's CRM account. This was generated when they connected their account.
	AccessToken string `queryParam:"style=form,explode=true,name=accessToken"`
	// Returns all fields including non-unifiable and custom fields under the "additional" property in the response
	AllFields *bool  `queryParam:"style=form,explode=true,name=allFields"`
	ID        string `queryParam:"style=form,explode=true,name=id"`
}

type GetUserRequest struct {
	QueryParams GetUserQueryParams
}

// GetUser200ApplicationJSON - OK
type GetUser200ApplicationJSON struct {
	// Users of the connected CRM platform. These are *not* the contacts or leads, but rather the user accounts from the connected CRM.
	User *shared.User `json:"user,omitempty"`
}

type GetUserResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	GetUser200ApplicationJSONObject *GetUser200ApplicationJSON
}
