// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/snyk-go/pkg/models/shared"
	"net/http"
)

type GetWebhookQueryParams struct {
	// The token for the customer's CRM account. This was generated when they connected their account.
	AccessToken *string `queryParam:"style=form,explode=true,name=accessToken"`
	WebhookID   *string `queryParam:"style=form,explode=true,name=webhookId"`
}

type GetWebhookRequest struct {
	QueryParams GetWebhookQueryParams
}

// GetWebhook200ApplicationJSON - OK
type GetWebhook200ApplicationJSON struct {
	Webhook *shared.WebhookMetadata `json:"webhook,omitempty"`
}

type GetWebhookResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	GetWebhook200ApplicationJSONObject *GetWebhook200ApplicationJSON
}
