// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PostLinkTokenSecurity struct {
	VesselAPIToken string `security:"scheme,type=apiKey,subtype=header,name=vessel-api-token"`
}

// PostLinkToken200ApplicationJSON - Create link token
type PostLinkToken200ApplicationJSON struct {
	LinkToken *string `json:"linkToken,omitempty"`
}

type PostLinkTokenResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Create link token
	PostLinkToken200ApplicationJSONObject *PostLinkToken200ApplicationJSON
}
