// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/snyk-go/pkg/models/shared"
	"net/http"
)

type PostNoteRequestBody struct {
	AccessToken string `json:"accessToken"`
	// Create a new Note. You may only associate a note with at most one entity of each type upon creation.
	Note shared.NoteCreate `json:"note"`
}

type PostNoteRequest struct {
	Request *PostNoteRequestBody `request:"mediaType=application/json"`
}

// PostNote200ApplicationJSON - OK
type PostNote200ApplicationJSON struct {
	ID string `json:"id"`
}

type PostNoteResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	PostNote200ApplicationJSONObject *PostNote200ApplicationJSON
}
