// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/snyk-go/pkg/models/shared"
	"net/http"
)

type PostWebhookRequestBody struct {
	AccessToken *string `json:"accessToken,omitempty"`
	// Information describing a webhook
	Webhook *shared.WebhookMetadataCreate `json:"webhook,omitempty"`
}

// PostWebhook200ApplicationJSON - OK
type PostWebhook200ApplicationJSON struct {
	Webhook *shared.WebhookMetadata `json:"webhook,omitempty"`
}

type PostWebhookResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	PostWebhook200ApplicationJSONObject *PostWebhook200ApplicationJSON
}
