// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/snyk-go/pkg/models/shared"
	"net/http"
)

type PostEventRequestBody struct {
	AccessToken string              `json:"accessToken"`
	Event       *shared.EventCreate `json:"event,omitempty"`
}

type PostEventRequest struct {
	Request *PostEventRequestBody `request:"mediaType=application/json"`
}

// PostEvent200ApplicationJSON - OK
type PostEvent200ApplicationJSON struct {
	ID string `json:"id"`
}

type PostEventResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	PostEvent200ApplicationJSONObject *PostEvent200ApplicationJSON
}
