// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/snyk-go/pkg/models/shared"
	"net/http"
)

// PostEventAttendee200ApplicationJSON - OK
type PostEventAttendee200ApplicationJSON struct {
	AccessToken   *string                     `json:"accessToken,omitempty"`
	EventAttendee *shared.EventAttendeeCreate `json:"eventAttendee,omitempty"`
}

type PostEventAttendeeResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	PostEventAttendee200ApplicationJSONObject *PostEventAttendee200ApplicationJSON
}
