// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

// PutContactRaw200ApplicationJSON - OK
type PutContactRaw200ApplicationJSON struct {
	ID string `json:"id"`
}

type PutContactRawResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// OK
	PutContactRaw200ApplicationJSONObject *PutContactRaw200ApplicationJSON
}
