// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type AccountAssociations struct {
	ContactIds []string `json:"contactIds"`
	DealIds    []string `json:"dealIds"`
	EventIds   []string `json:"eventIds"`
	LeadIds    []string `json:"leadIds"`
	NoteIds    []string `json:"noteIds"`
	TaskIds    []string `json:"taskIds"`
}

// Account - (Alias: company, organization) An organization involved with your business.
type Account struct {
	// Returned when `allFields` is set in the query params. Includes all data, untransformed, we recieved from the downstream CRM
	Additional map[string]interface{} `json:"additional,omitempty"`
	Address    *Address               `json:"address,omitempty"`
	// Not supported by Pipedrive
	AnnualRevenue *float64            `json:"annualRevenue,omitempty"`
	Associations  AccountAssociations `json:"associations"`
	// The date that the account was created
	CreatedTime time.Time `json:"createdTime"`
	// A description of this Company/Account. Not supported by Pipedrive
	Description *string `json:"description,omitempty"`
	ID          string  `json:"id"`
	// Not supported by Pipedrive
	Industry *string `json:"industry,omitempty"`
	// The date the account was last modified
	ModifiedTime time.Time `json:"modifiedTime"`
	Name         *string   `json:"name,omitempty"`
	// Id in the downstream CRM
	NativeID string `json:"nativeId"`
	// Not supported by Pipedrive
	NumberOfEmployees *float64 `json:"numberOfEmployees,omitempty"`
	// The primary phone number. Not supported by Pipedrive
	Phone *string `json:"phone,omitempty"`
	// Not supported by Pipedrive
	Website *string `json:"website,omitempty"`
}
