// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// ContactCreate - Properties that a contact can be created with
type ContactCreate struct {
	// Create any property in the downstream CRM, such as a custom or native property. For a list of all properties see /details.
	Additional map[string]interface{} `json:"additional,omitempty"`
	Email      *string                `json:"email,omitempty"`
	FirstName  *string                `json:"firstName,omitempty"`
	// Not supported by Pipedrive
	JobTitle    *string `json:"jobTitle,omitempty"`
	LastName    string  `json:"lastName"`
	MobilePhone *string `json:"mobilePhone,omitempty"`
	// The primary phone
	Phone *string `json:"phone,omitempty"`
}
