// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type ContactAssociations struct {
	AccountIds       []string `json:"accountIds"`
	DealIds          []string `json:"dealIds"`
	EventAttendeeIds []string `json:"eventAttendeeIds"`
	EventIds         []string `json:"eventIds"`
	LeadIds          []string `json:"leadIds"`
	NoteIds          []string `json:"noteIds"`
	TaskIds          []string `json:"taskIds"`
}

// Contact - Information about an individual affiliated with another CRM Object (e.g., a Lead, a Deal, etc)
type Contact struct {
	// Returned when `allFields` is set in the query params. Includes all data, untransformed, we recieved from the downstream CRM
	Additional   map[string]interface{} `json:"additional,omitempty"`
	Associations ContactAssociations    `json:"associations"`
	// The date that the contact was created
	CreatedTime time.Time `json:"createdTime"`
	Email       *string   `json:"email,omitempty"`
	FirstName   *string   `json:"firstName,omitempty"`
	ID          string    `json:"id"`
	// Not supported by Pipedrive.
	JobTitle *string `json:"jobTitle,omitempty"`
	LastName *string `json:"lastName,omitempty"`
	// The primary mobile phone number for this contact. Possibly the same as the phone number.
	MobilePhone *string `json:"mobilePhone,omitempty"`
	// The date the contact was last modified
	ModifiedTime time.Time `json:"modifiedTime"`
	// Id in the downstream CRM
	NativeID string `json:"nativeId"`
	// The primary phone number for this contact
	Phone *string `json:"phone,omitempty"`
}
