// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type CrmIntegrationIntegrationIDEnum string

const (
	CrmIntegrationIntegrationIDEnumSalesforce CrmIntegrationIntegrationIDEnum = "salesforce"
	CrmIntegrationIntegrationIDEnumHubspot    CrmIntegrationIntegrationIDEnum = "hubspot"
	CrmIntegrationIntegrationIDEnumPipedrive  CrmIntegrationIntegrationIDEnum = "pipedrive"
)

type CrmIntegration struct {
	// Base 64 data URI
	IconURL       *string                          `json:"iconURL,omitempty"`
	IntegrationID *CrmIntegrationIntegrationIDEnum `json:"integrationId,omitempty"`
	Name          *string                          `json:"name,omitempty"`
}
