// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type DealAssociations struct {
	AccountIds []string `json:"accountIds"`
	ContactIds []string `json:"contactIds"`
	EventIds   []string `json:"eventIds,omitempty"`
	NoteIds    []string `json:"noteIds"`
	TaskIds    []string `json:"taskIds"`
}

// Deal - (Alias: Opportunity) An object representing either the opportunity to sell a product to an Account, or in the case of an `isWon` deal, a product sold to an Account.
//
// *CRM Caveats*:
// - Pipedrive: Users must have "Deal probability" turned on for the given pipeline for probability to be configurable and returned.
type Deal struct {
	// Returned when `allFields` is set in the query params. Includes all data, untransformed, we recieved from the downstream CRM
	Additional map[string]interface{} `json:"additional,omitempty"`
	// Total deal money value
	Amount       *float64         `json:"amount,omitempty"`
	Associations DealAssociations `json:"associations"`
	// When this deal is projected to be closed
	CloseDate time.Time `json:"closeDate"`
	// The date that the deal was created
	CreatedTime time.Time `json:"createdTime"`
	// probability * amount. This is a computed property
	ExpectedRevenue *float64 `json:"expectedRevenue,omitempty"`
	ID              string   `json:"id"`
	// If this deal is closed (either closed-won or closed-lost). This is a computed property based on stage
	IsClosed *bool `json:"isClosed,omitempty"`
	// If this deal has been won. This is a computed property based on stage
	IsWon *bool `json:"isWon,omitempty"`
	// The date the deal was last modified
	ModifiedTime time.Time `json:"modifiedTime"`
	// Optional name for this deal
	Name *string `json:"name,omitempty"`
	// Id in the downstream CRM
	NativeID string `json:"nativeId"`
	// Decimal probability of closing this deal.
	Probability *string `json:"probability,omitempty"`
	// The stage of the pipeline the deal is in. See /deal/details for possible values
	Stage *string `json:"stage,omitempty"`
}
