// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type DealCreate struct {
	// The Id of the account to associate this deal with
	AccountID *string `json:"accountId,omitempty"`
	// Create any property in the downstream CRM, such as a custom or native property. For a list of all properties see /details.
	Additional map[string]interface{} `json:"additional,omitempty"`
	Amount     *float64               `json:"amount,omitempty"`
	CloseDate  string                 `json:"closeDate"`
	Name       string                 `json:"name"`
	// Decimal probability of closing the deal
	Probability *string `json:"probability,omitempty"`
	// The stage the deal is in. See /deal/details for possible value
	Stage *string `json:"stage,omitempty"`
}
