// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type EventAttendeeCreate struct {
	// Create any property in the downstream CRM, such as a custom or native property. For a list of all properties see /details.
	Additional map[string]interface{} `json:"additional,omitempty"`
	// The object type of the associated object (e.g., Contact, Lead, etc) or Other if this Attendee is not associated with a CRM object
	AssociatedObjectType string `json:"associatedObjectType"`
	// Required unless email is present and CRM supports "Other" for associatedObjectType
	AssociationID *string `json:"associationId,omitempty"`
	// Required if associationId is not present and the CRM supports "Other" for attendee associatedObjectType
	Email   *string `json:"email,omitempty"`
	EventID string  `json:"eventId"`
	Status  *string `json:"status,omitempty"`
}
