// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type EventCreate struct {
	AccountID *string `json:"accountId,omitempty"`
	// Create any property in the downstream CRM, such as a custom or native property. For a list of all properties see /details.
	Additional  map[string]interface{} `json:"additional,omitempty"`
	ContactID   *string                `json:"contactId,omitempty"`
	DealID      *string                `json:"dealId,omitempty"`
	Description *string                `json:"description,omitempty"`
	EndDateTime string                 `json:"endDateTime"`
	// Not supported by HubSpot and Pipedrive
	IsAllDayEvent *bool   `json:"isAllDayEvent,omitempty"`
	LeadID        *string `json:"leadId,omitempty"`
	Location      *string `json:"location,omitempty"`
	OwnerUserID   *string `json:"ownerUserId,omitempty"`
	StartDateTime string  `json:"startDateTime"`
	Subject       *string `json:"subject,omitempty"`
	Type          *string `json:"type,omitempty"`
}
