// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type FieldOptions struct {
	Key  *string     `json:"key,omitempty"`
	Name interface{} `json:"name,omitempty"`
}

type FieldTypeEnum string

const (
	FieldTypeEnumString       FieldTypeEnum = "string"
	FieldTypeEnumNumber       FieldTypeEnum = "number"
	FieldTypeEnumDatetime     FieldTypeEnum = "datetime"
	FieldTypeEnumDate         FieldTypeEnum = "date"
	FieldTypeEnumBoolean      FieldTypeEnum = "boolean"
	FieldTypeEnumReference    FieldTypeEnum = "reference"
	FieldTypeEnumPhone        FieldTypeEnum = "phone"
	FieldTypeEnumURL          FieldTypeEnum = "url"
	FieldTypeEnumID           FieldTypeEnum = "id"
	FieldTypeEnumEmail        FieldTypeEnum = "email"
	FieldTypeEnumPercent      FieldTypeEnum = "percent"
	FieldTypeEnumSingleselect FieldTypeEnum = "singleselect"
	FieldTypeEnumMultiselect  FieldTypeEnum = "multiselect"
	FieldTypeEnumAddress      FieldTypeEnum = "address"
	FieldTypeEnumDaterange    FieldTypeEnum = "daterange"
	FieldTypeEnumDecimal      FieldTypeEnum = "decimal"
	FieldTypeEnumTime         FieldTypeEnum = "time"
	FieldTypeEnumObject       FieldTypeEnum = "object"
)

// Field - (Alias: property) A field is a key-value pair on a CRM Object that provides information about that object.
type Field struct {
	// If this field can be used when creating the object
	Creatable bool `json:"creatable"`
	// If this field is a custom field
	Custom bool `json:"custom"`
	// If this field is an array
	IsArray *bool `json:"isArray,omitempty"`
	// The key in the CRM object (ex: annualRevenue, numberOfEmployees, etc)
	Key string `json:"key"`
	// The display name of this field (ex: number of employees, annual revenue, etc)
	Name string `json:"name"`
	// Possible options for this field
	Options []FieldOptions `json:"options,omitempty"`
	Type    FieldTypeEnum  `json:"type"`
	// If this is a field we've unified across CRMs
	Universal bool `json:"universal"`
	// If this field can be updated
	Updatable bool `json:"updatable"`
}
