// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type LeadCreate struct {
	// Name of the Account associated with this lead. Not supported for Pipedrive. Defaults to `[TODO]: Fill in Company Name` in Salesforce
	Account *string `json:"account,omitempty"`
	// Create any property in the downstream CRM, such as a custom or native property. For a list of all properties see /details.
	Additional map[string]interface{} `json:"additional,omitempty"`
	Email      *string                `json:"email,omitempty"`
	FirstName  *string                `json:"firstName,omitempty"`
	JobTitle   *string                `json:"jobTitle,omitempty"`
	LastName   string                 `json:"lastName"`
	// The primary mobile phone number for this lead. Possibly the same as the phone number.
	MobilePhone *string `json:"mobilePhone,omitempty"`
	// The primary phone number for this lead
	Phone *string `json:"phone,omitempty"`
}
