// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type LeadAssociations struct {
	AccountIds       []string `json:"accountIds"`
	ContactIds       []string `json:"contactIds"`
	EventAttendeeIds []string `json:"eventAttendeeIds"`
	EventIds         []string `json:"eventIds"`
	NoteIds          []string `json:"noteIds"`
	TaskIds          []string `json:"taskIds"`
}

// Lead - A Lead represents an individual, or sometimes an organization, that is interested in purchasing your product (i.e., is a potential Deal).
//
// *CRM Caveats*:
// - HubSpot: we consider contacts with the `leadStatus` set to be leads.
type Lead struct {
	// Name of the Account associated with this lead
	Account *string `json:"account,omitempty"`
	// Returned when `allFields` is set in the query params. Includes all data, untransformed, we recieved from the downstream CRM
	Additional   map[string]interface{} `json:"additional,omitempty"`
	Associations LeadAssociations       `json:"associations"`
	// The date that the lead was created
	CreatedTime time.Time `json:"createdTime"`
	Email       *string   `json:"email,omitempty"`
	FirstName   *string   `json:"firstName,omitempty"`
	ID          string    `json:"id"`
	JobTitle    *string   `json:"jobTitle,omitempty"`
	LastName    *string   `json:"lastName,omitempty"`
	// The primary mobile phone number for this lead. Possibly the same as the phone number.
	MobilePhone *string `json:"mobilePhone,omitempty"`
	// The date the lead was last modified
	ModifiedTime time.Time `json:"modifiedTime"`
	// Id in the downstream CRM
	NativeID string `json:"nativeId"`
	// The primary phone
	Phone *string `json:"phone,omitempty"`
}
