// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type NoteAssociations struct {
	AccountIds []string `json:"accountIds"`
	ContactIds []string `json:"contactIds"`
	DealIds    []string `json:"dealIds"`
	LeadIds    []string `json:"leadIds"`
	// The Id of the User that owns this note
	OwnerUserID string `json:"ownerUserId"`
}

// Note - A Note attached to some CRM Object.
type Note struct {
	// Returned when `allFields` is set in the query params. Includes all data, untransformed, we recieved from the downstream CRM
	Additional   map[string]interface{} `json:"additional,omitempty"`
	Associations NoteAssociations       `json:"associations"`
	// The body of the note
	Content *string `json:"content,omitempty"`
	// The date that the note was created
	CreatedTime time.Time `json:"createdTime"`
	ID          string    `json:"id"`
	// The date the note was last modified
	ModifiedTime time.Time `json:"modifiedTime"`
	// Id in the downstream CRM
	NativeID string `json:"nativeId"`
}
