// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// NoteCreate - Create a new Note. You may only associate a note with at most one entity of each type upon creation.
type NoteCreate struct {
	// Required unless leadId/dealId/contactId are specified.
	AccountID *string `json:"accountId,omitempty"`
	// Create any property in the downstream CRM, such as a custom or native property. For a list of all properties see /details.
	Additional map[string]interface{} `json:"additional,omitempty"`
	// Required unless leadId/accountId/dealId are specified.
	ContactID *string `json:"contactId,omitempty"`
	Content   string  `json:"content"`
	// Required unless leadId/accountId/contactId are specified.
	DealID *string `json:"dealId,omitempty"`
	// Required unless dealId/accountId/contactId are specified.
	LeadID *string `json:"leadId,omitempty"`
	// The user to assign this note to. If there is no userId provided, the behavior is defined by the downstream system (either assigned to no user or to the user that installed the app).
	UserID *string `json:"userId,omitempty"`
}
