// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Security struct {
	VesselAPIToken string `security:"scheme,type=apiKey,subtype=header,name=vessel-api-token"`
}
