// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type TaskCreate struct {
	AccountID *string `json:"accountId,omitempty"`
	// Create any property in the downstream CRM, such as a custom or native property. For a list of all properties see /details.
	Additional map[string]interface{} `json:"additional,omitempty"`
	Body       *string                `json:"body,omitempty"`
	ContactID  *string                `json:"contactId,omitempty"`
	// Can only set either leadId or dealId but not both.
	DealID  *string `json:"dealId,omitempty"`
	DueDate *string `json:"dueDate,omitempty"`
	// If both `isDone` and `status` are included, `isDone` will take precedence and automatically set `status` to either the default or a 'closed' status depending on the `isDone` value.
	IsDone *bool `json:"isDone,omitempty"`
	// Can only set either leadId or dealId but not both.
	LeadID *string `json:"leadId,omitempty"`
	// not supported by Pipedrive
	Priority *string `json:"priority,omitempty"`
	// not supported by Pipedrive
	Status  *string `json:"status,omitempty"`
	Subject *string `json:"subject,omitempty"`
	// The user to assign this note to. If there is no userId provided, the behavior is defined by the downstream system (either assigned to no user or to the user that installed the app).
	UserID *string `json:"userId,omitempty"`
}
