// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type TaskAssociations struct {
	AccountIds []string `json:"accountIds"`
	ContactIds []string `json:"contactIds"`
	DealIds    []string `json:"dealIds"`
	LeadIds    []string `json:"leadIds"`
	// The Id of the User that owns this Task
	OwnerUserID string `json:"ownerUserId"`
}

// Task - A task attached to some CRM object
type Task struct {
	// Returned when `allFields` is set in the query params. Includes all data, untransformed, we recieved from the downstream CRM
	Additional   map[string]interface{} `json:"additional,omitempty"`
	Associations TaskAssociations       `json:"associations"`
	Body         *string                `json:"body,omitempty"`
	// The date that the task was created
	CreatedTime time.Time `json:"createdTime"`
	DueDate     *string   `json:"dueDate,omitempty"`
	ID          string    `json:"id"`
	IsDone      *bool     `json:"isDone,omitempty"`
	// The date the task was last modified
	ModifiedTime time.Time `json:"modifiedTime"`
	// Id in the downstream CRM
	NativeID string `json:"nativeId"`
	// not supported by Pipedrive
	Priority *string `json:"priority,omitempty"`
	// not supported by Pipedrive
	Status  *string `json:"status,omitempty"`
	Subject *string `json:"subject,omitempty"`
}
