// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

type UserAssociations struct {
	EventIds []string `json:"eventIds"`
	NoteIds  []string `json:"noteIds"`
	TaskIds  []string `json:"taskIds"`
}

// User - Users of the connected CRM platform. These are *not* the contacts or leads, but rather the user accounts from the connected CRM.
type User struct {
	// Returned when `allFields` is set in the query params. Includes all data, untransformed, we recieved from the downstream CRM
	Additional   map[string]interface{} `json:"additional,omitempty"`
	Associations UserAssociations       `json:"associations"`
	// The date that the user was created
	CreatedTime time.Time `json:"createdTime"`
	Email       *string   `json:"email,omitempty"`
	FirstName   *string   `json:"firstName,omitempty"`
	// Unique identifier for the given user
	ID       string  `json:"id"`
	LastName *string `json:"lastName,omitempty"`
	// The date the user was last modified
	ModifiedTime time.Time `json:"modifiedTime"`
	// Id in the downstream CRM
	NativeID string `json:"nativeId"`
}
