// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// WebhookMetadataCreate - Information describing a webhook
type WebhookMetadataCreate struct {
	// a valid URL
	WebhookURL *string `json:"webhookUrl,omitempty"`
}
